### PR TITLE
Fix the path for npm package

### PR DESCRIPTION
**Pull request by zalmoxisus**
Before it couldn't be imported.

### CODE REVIEW

**Comment by zalmoxisus** [comment]
BTW, is the package from npm the same as from github? The version and dependencies differ.

**Comment by andrerpena** [comment]
Oh! Thank you very much for this!
About the version of the NPM package, they should be the same. I'm going to fix that right now.

**Comment by andrerpena** [comment]
Oh.. I actually had the versioing right on my machine but I haven't published that. Thanks for poiting that out. Anyway.. I'm publishing the 1.7 version right now with your package.json fix

**Comment by andrerpena** [comment]
Also, I realized the demo wasn't actually working correctly locally both on development and production mode. I just fixed it. I also added documentation about running the demo locally: https://github.com/gearz-lab/react-vnav/blob/master/readme.md

**Pull request merged**
